# Generated by Django 4.1.3 on 2022-11-21 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('elevatorID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currentfloor', models.IntegerField()),
                ('requested_floor', models.IntegerField()),
                ('elevator_status', models.CharField(max_length=100)),
            ],
        ),
    ]
